config/routes.rb
RegistryApp::Application.routes.draw do
  resources :types

  root :to => "Pages#home"
  get "/steps" => "Pages#steps", :as => :steps
  get "/approval" => "Pages#approval", :as => :approval

  resources :users
  get "/register" => "Users#new", :as => :register

  get "/products/new" => "Products#new", :as => :new_product
  post "/products" => "Products#create", :as => :products
  get "/products" => "Products#index", :as => :products
  get "/products/:product_id" => "Products#show", :as => :product
  get "/products/:product_id/edit" => "Products#edit", :as => :edit_product
  put "/products/:product_id" => "Products#update", :as => :product
  delete "/products/:product_id" => "Products#destroy", :as => :product


  get "/sign-in" => "Sessions#new", :as => :sign_in
  post "/sessions" => "Sessions#create", :as => :sessions
  delete "/sign-out" => "Sessions#destroy", :as => :sign_out

  post "/registries" => "Registries#create", :as => :registries
  put "/registries/:registry_id" => "Registries#update", :as => :registry
  delete "/registries/:registry_id" => "Registry#destroy", :as => :registry
  get "/users/:id/registry" => "Registries#show", :as => :user_registry

  get "/setup/account-information" => "Wizard#account_information", :as => :wizard_account
  get "/setup/lifestyle" => "Wizard#choose_lifestyle", :as => :wizard_lifestyle

  get "/users/:id/registry/:product_id" => "RegistryProducts#show", :as => :registry_product
  put "/users/:id/registry/:product_id" => "RegistryProducts#update", :as => :registry_product

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simplstry</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
  <link href='http://fonts.googleapis.com/css?family=Roboto:400' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!---->
   <div class="navbar navbar-inverse navbar-fixed-top">
   <div class="navbar-inner2 signin-bar">
   <div class="container">
    <div class="span4 offset6">
    <% if signed_in? %>
      <% if has_registry? %>
        <%= link_to "View Registry", user_registry_url(current_user) %>
      <% end %>
      <%= link_to "Sign Out", sign_out_url, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", "/register" %>
      <%= link_to "Sign In", sign_in_url %>
    <% end %>
    </div>
    </div><!--/.container-->
    </div><!--/.navbar-inner-->
    </div>
    
    <div class="navbar-inner grad">
   <div class="container">
    <div class="span4 logo-cont">
       <a href="/"><img src="/assets/simplstry-logo.png" class="visible-desktop"></a>
    <a href="/"><img src="/assets/simplstry-mobile.png" class="visible-phone visible-tablet"></a>
    </div>
    </div><!--/.container-->
    </div><!--/.navbar-inner-->
      <%= yield %>
    <div class="container footer">
     <div class="row footer-row">
   <div class="span5 offset1 copyright">&copy; 2013 Simplstry. All rights reserved.</div>
   <div class="span6 contact-box">
   <div class="contact-box-inner">Contact Us <a href="mailto:simplstry@mail.com"><img src="/assets/email-ico.png" class="btm-icons"></a><a href="http://twitter.com/simplstry"><img src="/assets/white-twitter.png"  class="btm-icons" width="70" height="39"></a>    </div>
        </div>
      </div>
    </div>
  </div>
 <%= javascript_include_tag "application" %>
</body>
</html>